### ISSUE TITLE
Cannot convert DeviceMemory to other types

### ISSUE THREAD

**Issue by loostrum** [nlesc-recruit/cudawrappers#243]
**Describe the bug**
DeviceMemory objects explicitly forbid converting device-only memory to other types, see [here](https://github.com/nlesc-recruit/cudawrappers/blob/1ef0ac8ab1095eb7a5ccf2f669b27920e811850a/include/cudawrappers/cu.hpp#L464C12-L475C12).

I'm wondering why this is the case? It may be lack of knowledge of the CUDA APIs on my part, but it seems I _can_ convert `DeviceMemory` to `CUdeviceptr` and from there to any other type. Maybe there's a good reason this should not be allowed, but in my example code that did seem to work fine.

**To Reproduce**
I'm trying to use cudawrappers while calling a kernel with the runtime API. The kernel accepts an argument with a custom type `A_t`. For `HostMemory`, I can simply do 
```
cu::HostMemory h_a(sizeof(A_t));
A_t *a = (A_t *)h_a;
```

but for `DeviceMemory` I need to do the following to get it to work:
```
cu::DeviceMemory d_a(sizeof(A_t));
CUdeviceptr tmp = (CUdeviceptr)d_a;
A_t *a = (A_t *)tmp;
```

Just for completeness, to actually run into the error:
```
cu::DeviceMemory d_a(sizeof(A_t));
A_t *a = (A_t *)d_a;
```
gives `Cannot return memory of type CU_MEMORYTYPE_DEVICE as pointer.`

**Comment by csbnw** [comment]
How about using the `DeviceMemory::parameter()` [function](https://github.com/nlesc-recruit/cudawrappers/blob/1ef0ac8ab1095eb7a5ccf2f669b27920e811850a/include/cudawrappers/cu.hpp#L458)? 
So the code would look like this:
```
cu::DeviceMemory d_a(sizeof(A_t));
A_t *a = (A_t *)d_a.parameter();
```
Or in C++ fashion:
```
cu::DeviceMemory d_a(sizeof(A_t));
A_t *a = static_cast<A_t *>(d_a.parameter());
```

**Comment by loostrum** [comment]
I tried using `.parameter()` first, but that results in `an illegal memory access was encountered` upon calling the kernel.

**Comment by csbnw** [comment]
The `DeviceMemory` class has a [constructor](https://github.com/nlesc-recruit/cudawrappers/blob/1ef0ac8ab1095eb7a5ccf2f669b27920e811850a/include/cudawrappers/cu.hpp#L452) that accepts a `HostMemory`. The `HostMemory` can be casted to anything using [this](https://github.com/nlesc-recruit/cudawrappers/blob/1ef0ac8ab1095eb7a5ccf2f669b27920e811850a/include/cudawrappers/cu.hpp#L269) operator. 

So maybe you can use this code to 1) allocate memory on the host, 2) get the pointer so that you can access the 'raw' memory and 3) also have an object that you can use to pass to your kernel.
```
cu::HostMemory h_a(sizeof(A_t));
A_t *a = static_cast<A_t *>(h_a);
cu::DeviceMemory d_a(h_a);
```

**Comment by loostrum** [comment]
Thanks! With those options I'll get it working. In any case, not a bug so I'll close this issue.
