### ISSUE TITLE
Software and hardware configurations

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#6]
We need a list of hardware and software used in development and testing. Please add the information below as a comment.

- Infrastructure details: < AWS, DAS5, DAS6 etc.>
- Operating system details:< Windows 11, Ubuntu 21.10, Amazon Linux, macOS>
- CUDA version and GPU device (paste output of `nvidia-smi`):

**Comment by john-romein** [comment]
We can test this on DAS-6/DAS-5, but I think it should be usable on any NVIDIA GPU system.  Which other platforms/OSses are available for testing?  Can we test it on Windows and/or macOS?   I do not expect portability issues for most code, except for runtime compilation   I guess we should support CUDA 10 and later, and any GPU since the Pascal generation.

**Comment by svlugt** [comment]
- At least test on DAS6, optionally DAS5
- Would be nice if you have another (Linux) system available for testing
- At least support Linux, testing on Windows and macOS would be nice to have
- Support CUDA 10 and up, support GPU architecture Pascal and up
- We can easily support loading of different CUDA version on DAS6 for CI testing. It would be good to test multiple different versions of CUDA in the CI test.

**Comment by fdiblen** [comment]
Closing the issue as this is super seeded by #34.
